import type { CustomerData, PortfolioEntry } from "./types";

export const MOCK_KLARNA: CustomerData = {
  slug: "klarna",
  config: {
    name: "Klarna",
    hubspot_company_record_id: "19069457924",
    slack_channels: ["#customer-klarna"],
    revenue_lines: [
      {
        label: "Klarna US",
        hubspot_deal_record_ids: ["20303327145"],
        linear_projects: ["klarna-us-mvno-19069457924-14774e3ed18c"],
        slack_channels: [],
        lightdash_dashboards: [],
      },
      {
        label: "Klarna UK",
        hubspot_deal_record_ids: ["37968818055"],
        linear_projects: ["klarna-uk-mvno-19069457924-010463626266"],
        slack_channels: [],
        lightdash_dashboards: [],
      },
      {
        label: "Klarna SE",
        hubspot_deal_record_ids: [],
        linear_projects: [],
        slack_channels: [],
        lightdash_dashboards: [],
      },
    ],
    linear_initiatives: ["am-klarna-account-cb4fd5a5abb5"],
    linear_projects: ["klarna-requests-eb470d6346eb"],
    google_sheets: [{ label: "Klarna forecast", url: "#" }],
  },
  health: "green",
  deals: [
    {
      label: "Klarna US",
      health: "green",
      hubspotStage: "S3 Negotiation",
      hubspotStageIndex: 5,
      dealOwner: "David F.",
      linearProjectOwner: "Max B.",
      dri: "Max B.",
      driSource: "linear",
      arr: 124000,
      activations: 2340,
      goLiveProbability: "High",
      goLiveDate: "Jun 2026",
      linearIssueCount: 2,
      miniArrTrend: [
        { month: "Jan", actual: 72000, forecast: 72000 },
        { month: "Feb", actual: 78000, forecast: 76000 },
        { month: "Mar", actual: 84000, forecast: 82000 },
        { month: "Apr", actual: null, forecast: 88000 },
        { month: "May", actual: null, forecast: 95000 },
        { month: "Jun", actual: null, forecast: 102000 },
      ],
    },
    {
      label: "Klarna UK",
      health: "yellow",
      hubspotStage: "S2 Proposal",
      hubspotStageIndex: 4,
      dealOwner: "Tilly M.",
      linearProjectOwner: "Max B.",
      dri: "Max B.",
      driSource: "linear",
      arr: 86000,
      activations: 1120,
      goLiveProbability: "Med",
      goLiveDate: "Q3 2026",
      linearIssueCount: 4,
      miniArrTrend: [
        { month: "Jan", actual: 30000, forecast: 32000 },
        { month: "Feb", actual: 35000, forecast: 38000 },
        { month: "Mar", actual: 42000, forecast: 45000 },
        { month: "Apr", actual: null, forecast: 52000 },
        { month: "May", actual: null, forecast: 60000 },
        { month: "Jun", actual: null, forecast: 68000 },
      ],
    },
    {
      label: "Klarna SE",
      health: "gray",
      hubspotStage: "Pursuing",
      hubspotStageIndex: 1,
      dealOwner: "Louisa K.",
      linearProjectOwner: null,
      dri: "Louisa K.",
      driSource: "hubspot",
      arr: null,
      activations: null,
      goLiveProbability: null,
      goLiveDate: null,
      linearIssueCount: 0,
      miniArrTrend: [],
    },
  ],
  linearIssues: [
    {
      id: "KLA-123",
      title: "API clone delay — blocked on connectivity partner",
      status: "In Progress",
      priority: 1,
      labels: ["flagged"],
      url: "#",
      assignee: "Max B.",
      market: "Klarna UK",
    },
    {
      id: "KLA-456",
      title: "Doc/presentation assets need review before S2 handoff",
      status: "Todo",
      priority: 2,
      labels: ["flagged"],
      url: "#",
      assignee: "Tilly M.",
      market: "Klarna UK",
    },
    {
      id: "KLA-789",
      title: "Pricing model v3 approved by Klarna procurement",
      status: "Done",
      priority: 3,
      labels: ["flagged"],
      url: "#",
      assignee: "David F.",
      market: "Klarna US",
    },
  ],
  arrData: [
    { month: "Jul", actual: 42000, forecast: 40000 },
    { month: "Aug", actual: 48000, forecast: 45000 },
    { month: "Sep", actual: 51000, forecast: 50000 },
    { month: "Oct", actual: 55000, forecast: 56000 },
    { month: "Nov", actual: 61000, forecast: 60000 },
    { month: "Dec", actual: 68000, forecast: 65000 },
    { month: "Jan", actual: 72000, forecast: 72000 },
    { month: "Feb", actual: 78000, forecast: 76000 },
    { month: "Mar", actual: 84000, forecast: 82000 },
    { month: "Apr", actual: null, forecast: 88000 },
    { month: "May", actual: null, forecast: 95000 },
    { month: "Jun", actual: null, forecast: 102000 },
  ],
  milestones: [
    { month: "Aug", label: "US Test Project Created", type: "product", deal: "Klarna US" },
    { month: "Oct", label: "US SOW Signed", type: "legal", deal: "Klarna US" },
    { month: "Nov", label: "UK Figma Received", type: "product", deal: "Klarna UK" },
    { month: "Jan", label: "US Pricing v3 Approved", type: "deal", deal: "Klarna US" },
    { month: "Mar", label: "UK S2 Proposal Sent", type: "deal", deal: "Klarna UK" },
    { month: "May", label: "US Contract Signing (est.)", type: "legal", deal: "Klarna US" },
    { month: "Jun", label: "US Go-Live Target", type: "launch", deal: "Klarna US" },
  ],
  slackActivity: {
    channels: [{ name: "#customer-klarna", messagesLast7d: 12, messagesLast30d: 48 }],
  },
  lastUpdated: "2026-04-17T14:00:00Z",
};

export const MOCK_REVOLUT: CustomerData = {
  slug: "revolut",
  config: {
    name: "Revolut",
    hubspot_company_record_id: "36930979171",
    slack_channels: ["#customer-revolut"],
    revenue_lines: [
      {
        label: "Revolut UK",
        hubspot_deal_record_ids: ["10326868488"],
        linear_projects: ["revolut-mobile-implementation-tracker-36930979171-00f79b1e5e31"],
        slack_channels: ["#ext-gigs-revolut-testing-feedback"],
        lightdash_dashboards: [],
      },
      {
        label: "Revolut Ireland",
        hubspot_deal_record_ids: [],
        linear_projects: [],
        slack_channels: [],
        lightdash_dashboards: [],
      },
    ],
    linear_initiatives: ["am-revolut-account-05769e519aa1"],
    linear_projects: [
      "revolut-bau-a7f49af5899d",
      "revolut-tech-debt-5a54a68c64f3",
      "revolut-launch-changes-ad3d8f5cd378",
    ],
    google_sheets: [],
  },
  health: "yellow",
  deals: [
    {
      label: "Revolut UK",
      health: "yellow",
      hubspotStage: "S4 Closed Won",
      hubspotStageIndex: 6,
      dealOwner: "David F.",
      linearProjectOwner: "Felipe I.",
      dri: "Felipe I.",
      driSource: "linear",
      arr: 340000,
      activations: 8500,
      goLiveProbability: "High",
      goLiveDate: "May 2026",
      linearIssueCount: 6,
      miniArrTrend: [
        { month: "Jan", actual: 280000, forecast: 290000 },
        { month: "Feb", actual: 300000, forecast: 310000 },
        { month: "Mar", actual: 320000, forecast: 330000 },
        { month: "Apr", actual: null, forecast: 350000 },
        { month: "May", actual: null, forecast: 370000 },
        { month: "Jun", actual: null, forecast: 400000 },
      ],
    },
    {
      label: "Revolut Ireland",
      health: "gray",
      hubspotStage: "Prospects",
      hubspotStageIndex: 2,
      dealOwner: null,
      linearProjectOwner: null,
      dri: null,
      driSource: null,
      arr: null,
      activations: null,
      goLiveProbability: "Low",
      goLiveDate: null,
      linearIssueCount: 0,
      miniArrTrend: [],
    },
  ],
  linearIssues: [
    {
      id: "REV-101",
      title: "Production webhook latency spikes during peak hours",
      status: "In Progress",
      priority: 1,
      labels: ["flagged"],
      url: "#",
      assignee: "Felipe I.",
      market: "Revolut UK",
    },
  ],
  arrData: [
    { month: "Jul", actual: 180000, forecast: 170000 },
    { month: "Aug", actual: 200000, forecast: 195000 },
    { month: "Sep", actual: 220000, forecast: 220000 },
    { month: "Oct", actual: 240000, forecast: 245000 },
    { month: "Nov", actual: 260000, forecast: 265000 },
    { month: "Dec", actual: 280000, forecast: 280000 },
    { month: "Jan", actual: 300000, forecast: 300000 },
    { month: "Feb", actual: 320000, forecast: 315000 },
    { month: "Mar", actual: 340000, forecast: 335000 },
    { month: "Apr", actual: null, forecast: 360000 },
    { month: "May", actual: null, forecast: 380000 },
    { month: "Jun", actual: null, forecast: 400000 },
  ],
  milestones: [
    { month: "Sep", label: "UK Contract Signed", type: "legal", deal: "Revolut UK" },
    { month: "Nov", label: "UK Integration Started", type: "product", deal: "Revolut UK" },
    { month: "Jan", label: "UK Beta Launch", type: "launch", deal: "Revolut UK" },
    { month: "Apr", label: "UK Full Launch (est.)", type: "launch", deal: "Revolut UK" },
  ],
  slackActivity: {
    channels: [{ name: "#customer-revolut", messagesLast7d: 24, messagesLast30d: 96 }],
  },
  lastUpdated: "2026-04-17T14:00:00Z",
};

export const MOCK_SANTANDER: CustomerData = {
  slug: "santander",
  config: {
    name: "Santander",
    hubspot_company_record_id: "",
    slack_channels: [],
    revenue_lines: [],
    linear_initiatives: [],
    linear_projects: [],
    google_sheets: [],
  },
  health: "gray",
  deals: [],
  linearIssues: [],
  arrData: [],
  milestones: [],
  slackActivity: { channels: [] },
  lastUpdated: "2026-04-17T14:00:00Z",
};

export const MOCK_PORTFOLIO: PortfolioEntry[] = [
  {
    slug: "klarna",
    name: "Klarna",
    health: "green",
    dealCount: 3,
    totalArr: 210000,
    stages: { "S3 Negotiation": 1, "S2 Proposal": 1, Pursuing: 1 },
    topLineHealth: ["green", "yellow", "gray"],
    lastUpdated: "2026-04-17T14:00:00Z",
  },
  {
    slug: "revolut",
    name: "Revolut",
    health: "yellow",
    dealCount: 2,
    totalArr: 340000,
    stages: { "S4 Closed Won": 1, Prospects: 1 },
    topLineHealth: ["yellow", "gray"],
    lastUpdated: "2026-04-17T14:00:00Z",
  },
  {
    slug: "santander",
    name: "Santander",
    health: "gray",
    dealCount: 0,
    totalArr: null,
    stages: {},
    topLineHealth: [],
    lastUpdated: "2026-04-17T14:00:00Z",
  },
];
